routes/admin.php
<?php


Route::prefix("admin")->as("admin.")->namespace("\\App\\Http\\Controllers\\Back")->group(function () {
    Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");

    Route::resource("children", "ChildrenController")->except(["store", "update"]);
    Route::match(["put","post"],"children","ChildrenController@store")->name("children.store");

    Route::resource("supports","SupportController")->only(['index',"show"]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage as Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/avatarNames', function () {
    $files = Storage::disk("avatars")->files();
    foreach ($files as $key => $file) {
        $files = Storage::disk("avatars")->files();
        Storage::disk("avatars")->move($file, "avatar_" . (string)($key + 1) . ".png");
    }
});

Route::get("/","HomeController@index")->name("home");
Route::get("getChildrenList","ChildrenController@childrenList")->name("children.list");
Route::post("children/submitSupportList","ChildrenController@storeSupportList")->name("children.list");
Route::get("supports/{uuid}","SupportController@show")->name("supports.show");

Auth::routes();

Route::get("sketch",function(){
    return view("sketch");
});


Route::get("import",function(){
    $children = \Maatwebsite\Excel\Facades\Excel::import(new \App\Imports\ChildrenImport(),storage_path("/emdad-excel/report.xlsx"));
    dd($children);
});

Route::get("about","FrontController@about")->name("about");
Route::get("contact","FrontController@contact")->name("contact");

app/Models/Support.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Support extends Model
{
    use HasFactory;

    protected $casts = [
        "selected_children" => "array"
    ];

    public function getUrlAttribute()
    {
        return route("supports.show",$this->uuid);
    }

    public function children(){
        return $this->belongsToMany(Child::class);
    }

    public function affiliate(){
        return $this->belongsTo(User::class,"affiliate_id")->withDefault(["name"=>"---"]);
    }

    public function user(){
        return $this->belongsTo(User::class)->withDefault(["name"=>"---"]);
    }
}

app/Http/Controllers/Back/ChildrenController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Child;
use Illuminate\Http\Request;

class ChildrenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        dd(Child::birthday()->toSql())
        $children = Child::paginate(50);
        return view("back.children.all",compact("children"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $child=new Child();
        return view("back.children.create",compact("child"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $child = $request->isMethod("post") ? new Child : Child::find($request->child_id);
        $child->birth_date_fa_f = $request->birth_date_fa_f;
        $child->fill($request->toArray());
        $child->save();

        return self::redirectWithSuccess(route("admin.children.index"),"انجام شد");
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function show(Child $child)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function edit(Child $child)
    {
        return view("back.children.edit",compact("child"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Child $child)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function destroy(Child $child)
    {
        //
    }
}

/*
[‎12/‎9/‎2020 6:43 PM] هادی اسماعیلی:
001110171
اعتبار مصارف هدفمندی یارانه ها
001110128
[‎12/‎9/‎2020 6:44 PM] هادی اسماعیلی:
اعتبار دولتی انتقالی سنواتی*/

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view("back.dashboard.index");
    }
}

app/Http/Controllers/Back/SupportController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Child;
use App\Models\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    public function index(){
        $supports = Support::orderBy("created_at","DESC")->withCount("children")->paginate(100);
        return view("back.supports.all",compact("supports"));
    }

    public function show(Support $support){
        return view("back.supports.show",compact("support"));
    }
}

app/Http/Controllers/SupportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    public function show($uuid)
    {
        $support = Support::whereUuid($uuid)->first();
        return view("front.supports.show",compact("support"));
    }
}

resources/views/back/supports/all.blade.php
@extends("back.layouts.app")
@section("content_header")
    @component("components.breadcrump",["items"=> ["Dashboard" =>route("admin.dashboard.index"),"current"=>"حمایت های ماهیانه"]])
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp

@section("content")
    <x-success></x-success>
    {{ $supports->render() }}
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>نام حامی</th>
                    <th>شماره موبایل</th>
                    <th>تعداد فرزند انتخاب شده</th>
                </tr>
                </thead>
                <tbody>
                @foreach($supports as $support)
                    <tr>
                        <td><a href="{{ route("admin.supports.show",$support) }}">{{ $support->supporter_name }}</a></td>
                        <td>{{ $support->supporter_mobile }}</td>
                        <td>{{ $support->children_count }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/back/supports/show.blade.php
@extends("back.layouts.app")
@section("content_header")
    @component("components.breadcrump",["items"=> ["Dashboard" =>route("admin.dashboard.index"),"current"=>"حمایت های ماهیانه"]])
    @endcomponent
@endsection
@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")


    <x-success></x-success>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <div>
                        <strong>نام حامی:</strong> {{ $support->supporter_name }}
                    </div>
                    <div>
                        <strong>موبایل حامی:</strong> {{ $support->supporter_mobile }}
                    </div>
                    <div>
                        <strong>کاربر معرف:</strong> {{ $support->affiliate->name }}
                    </div>
                    <div>
                        <strong>کاربر ثبت کننده:</strong>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    اطلاعات فرزندان
                </div>
                <div class="card-body">

                    <table class="table">
                        <thead>
                        <tr>
                            <th>نام</th>
                            <th>نام خانوادگی</th>
                            <th>کد ملی</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($support->children as $child)
                            <tr>
                                <td>{{$child->first_name}}</td>
                                <td>{{$child->last_name}}</td>
                                <td>{{$child->national_code}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection