routes/admin.php
<?php


Route::prefix("admin")->as("admin.")->namespace("\\App\\Http\\Controllers\\Back")->group(function () {
    Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");

    Route::resource("children", "ChildrenController")->except(["store", "update"]);
    Route::match(["put","post"],"children","ChildrenController@store")->name("children.store");

    Route::resource("supports","SupportController")->only(['index',"show"]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage as Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/avatarNames', function () {
    $files = Storage::disk("avatars")->files();
    foreach ($files as $key => $file) {
        $files = Storage::disk("avatars")->files();
        Storage::disk("avatars")->move($file, "avatar_" . (string)($key + 1) . ".png");
    }
});

Route::get("/","HomeController@index")->name("home");
Route::get("getChildrenList","ChildrenController@childrenList")->name("children.list");
Route::post("children/submitSupportList","ChildrenController@storeSupportList")->name("children.list");
Route::get("supports/{uuid}","SupportController@show")->name("supports.show");

Auth::routes();

Route::get("sketch",function(){
    return view("sketch");
});


Route::get("import",function(){
    $children = \Maatwebsite\Excel\Facades\Excel::import(new \App\Imports\ChildrenImport(),storage_path("/emdad-excel/report.xlsx"));
    dd($children);
});

Route::get("about","FrontController@about")->name("about");
Route::get("contact","FrontController@contact")->name("contact");

app/Models/Child.php
<?php

namespace App\Models;

use Baloot\EloquentHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Spatie\Tags\HasTags;

class Child extends Model
{
    use HasFactory;
    use EloquentHelper;
    use HasTags;


    const
        TYPE_EKRAM = 1,
        TYPE_MOHSENIN = 2;

    const
        SEX_MALE = 1,
        SEX_FEMALE = 2;

    protected $fillable = ["first_name", "last_name", "national_code", "birth_date", "about", "emotional_text", "sex", "city_id", "type","priority"];

    public function getNameAttribute()
    {
        return $this["first_name"];
    }

    public function getFullNameAttribute()
    {
        return $this["first_name"] . " " . $this["last_name"];
    }

    public function getImageUrlAttribute()
    {
        return asset("images/avatars/avatar_" . $this["id"] % 250 . ".png");
    }

    public function getTypeReadableAttribute()
    {
        return ([self::TYPE_EKRAM => "ایتام", self::TYPE_MOHSENIN => "محسنین"])[$this["type"]] ?? "";
    }

    public function getSexReadableAttribute()
    {
        return ([self::SEX_MALE => "پسر", self::SEX_FEMALE => "دختر"])[$this["sex"]] ?? "";
    }

    public function getCityAttribute()
    {
        return "کاشمر";
    }

    public function getAgeAttribute()
    {
        return \Carbon\Carbon::parse($this["birth_date"])->age;
    }

    protected $casts = [
        "birth_date" => "date",
    ];


    public function scopeBirthday($q)
    {

        $dateBegin = now()->subDays(2);
        $dateEnd = now()->addDays(10);

        $yearBegin = $dateBegin->year;

        return $q->whereRaw(
            "DATE_FORMAT(`children`.`birth_date`,'{$yearBegin}-%m-%d') > '"
            . $dateBegin->format("Y-m-d")
            . "' and "
            . "DATE_FORMAT(`children`.`birth_date`,'{$yearBegin}-%m-%d') < '" . $dateEnd->format("Y-m-d") . "'"

        );
    }


}

app/Models/Support.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Support extends Model
{
    use HasFactory;

    protected $casts = [
        "selected_children" => "array"
    ];

    public function getUrlAttribute()
    {
        return route("supports.show",$this->uuid);
    }

    public function children(){
        return $this->belongsToMany(Child::class);
    }

    public function affiliate(){
        return $this->belongsTo(User::class,"affiliate_id")->withDefault(["name"=>"---"]);
    }

    public function user(){
        return $this->belongsTo(User::class)->withDefault(["name"=>"---"]);
    }
}

app/Http/Controllers/Back/SupportController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Child;
use App\Models\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    public function index(){
        $supports = Support::orderBy("created_at","DESC")->withCount("children")->paginate(100);
        return view("back.supports.all",compact("supports"));
    }

    public function show(Support $support){
        return view("back.supports.show",compact("support"));
    }
}

app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FrontController extends Controller
{
    public function about()
    {
        return view("front.about");
    }
    public function contact()
    {
        return view("front.contact");
    }
}

app/Http/Controllers/SupportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    public function show($uuid)
    {
        $support = Support::whereUuid($uuid)->first();
        return view("front.supports.show",compact("support"));
    }
}

resources/views/front/supports/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="mb-5 ">
        <div class="container mb-5 pb-5 mb-5">
            <div class="card shadow mt-5 mb-5">
                <div class="card-body pb-0">
                    <h4>خیر گرامی، از شما به خاطر این اقدام نیک و مبارک ممنونیم ..</h4>
                    <p>همکاران ما در واحد اکرام ایتام و محسنین به زودی با شما (از طریق شماره ای که اعلام کرده اید) تماس خواهند گرفت و نحوه واریز وجه و حمایت را به شما توضیح خواهند داد.</p>
                    <div><strong>نام خیر:</strong> {{ $support->supporter_name }} </div>
                    <div><strong>شماره موبایل:</strong>{{ $support->supporter_mobile }}</div>
                    <div><strong>فرزندان معنوی شما:</strong></div>
                    <div>
                        <table class="table stripped hover">
                            <thead>
                            <tr>
                                <th>نام فرزند</th>
                                <th>سن</th>
                                <th>تولد</th>
                                <th>شهر</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($support->children as $child)
                                <tr>
                                    <td>{{ $child->full_name }}</td>
                                    <td>{{ $child->age  }}</td>
                                    <td>{{ $child->birth_date_fa->format(" %d %B %Y")  }}</td>
                                    <td>{{ $child->city  }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row  justify-content-center">
                        <div class="col-6 col-sm-6 col-md-3 pt-5">
                            <img src="{{ asset("svg/kindness.svg") }}" alt="" class="w-100">
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
@endsection