routes/admin.php
<?php


Route::prefix("admin")->as("admin.")->namespace("\\App\\Http\\Controllers\\Back")->group(function () {
    Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");

    Route::resource("children", "ChildrenController")->except(["store", "update"]);
    Route::match(["put","post"],"children","ChildrenController@store")->name("children.store");

    Route::resource("supports","SupportController")->only(['index',"show"]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage as Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/avatarNames', function () {
    $files = Storage::disk("avatars")->files();
    foreach ($files as $key => $file) {
        $files = Storage::disk("avatars")->files();
        Storage::disk("avatars")->move($file, "avatar_" . (string)($key + 1) . ".png");
    }
});

Route::get("/","HomeController@index")->name("home");
Route::get("getChildrenList","ChildrenController@childrenList")->name("children.list");
Route::post("children/submitSupportList","ChildrenController@storeSupportList")->name("children.list");
Route::get("supports/{uuid}","SupportController@show")->name("supports.show");

Auth::routes();

Route::get("sketch",function(){
    return view("sketch");
});


Route::get("import",function(){
    $children = \Maatwebsite\Excel\Facades\Excel::import(new \App\Imports\ChildrenImport(),storage_path("/emdad-excel/report.xlsx"));
    dd($children);
});

Route::get("about","FrontController@about")->name("about");
Route::get("contact","FrontController@contact")->name("contact");

app/Models/Child.php
<?php

namespace App\Models;

use Baloot\EloquentHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Spatie\Tags\HasTags;

class Child extends Model
{
    use HasFactory;
    use EloquentHelper;
    use HasTags;


    const
        TYPE_EKRAM = 1,
        TYPE_MOHSENIN = 2;

    const
        SEX_MALE = 1,
        SEX_FEMALE = 2;

    protected $fillable = ["first_name", "last_name", "national_code", "birth_date", "about", "emotional_text", "sex", "city_id", "type","priority"];

    public function getNameAttribute()
    {
        return $this["first_name"];
    }

    public function getFullNameAttribute()
    {
        return $this["first_name"] . " " . $this["last_name"];
    }

    public function getImageUrlAttribute()
    {
        return asset("images/avatars/avatar_" . $this["id"] % 250 . ".png");
    }

    public function getTypeReadableAttribute()
    {
        return ([self::TYPE_EKRAM => "ایتام", self::TYPE_MOHSENIN => "محسنین"])[$this["type"]] ?? "";
    }

    public function getSexReadableAttribute()
    {
        return ([self::SEX_MALE => "پسر", self::SEX_FEMALE => "دختر"])[$this["sex"]] ?? "";
    }

    public function getCityAttribute()
    {
        return "کاشمر";
    }

    public function getAgeAttribute()
    {
        return \Carbon\Carbon::parse($this["birth_date"])->age;
    }

    protected $casts = [
        "birth_date" => "date",
    ];


    public function scopeBirthday($q)
    {

        $dateBegin = now()->subDays(2);
        $dateEnd = now()->addDays(10);

        $yearBegin = $dateBegin->year;

        return $q->whereRaw(
            "DATE_FORMAT(`children`.`birth_date`,'{$yearBegin}-%m-%d') > '"
            . $dateBegin->format("Y-m-d")
            . "' and "
            . "DATE_FORMAT(`children`.`birth_date`,'{$yearBegin}-%m-%d') < '" . $dateEnd->format("Y-m-d") . "'"

        );
    }


}

app/Http/Controllers/Back/ChildrenController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Child;
use Illuminate\Http\Request;

class ChildrenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        dd(Child::birthday()->toSql())
        $children = Child::paginate(50);
        return view("back.children.all",compact("children"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $child=new Child();
        return view("back.children.create",compact("child"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $child = $request->isMethod("post") ? new Child : Child::find($request->child_id);
        $child->birth_date_fa_f = $request->birth_date_fa_f;
        $child->fill($request->toArray());
        $child->save();

        return self::redirectWithSuccess(route("admin.children.index"),"انجام شد");
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function show(Child $child)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function edit(Child $child)
    {
        return view("back.children.edit",compact("child"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Child $child)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Child $child
     * @return \Illuminate\Http\Response
     */
    public function destroy(Child $child)
    {
        //
    }
}

/*
[‎12/‎9/‎2020 6:43 PM] هادی اسماعیلی:
001110171
اعتبار مصارف هدفمندی یارانه ها
001110128
[‎12/‎9/‎2020 6:44 PM] هادی اسماعیلی:
اعتبار دولتی انتقالی سنواتی*/

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view("back.dashboard.index");
    }
}

app/Http/Controllers/Back/SupportController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Child;
use App\Models\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    public function index(){
        $supports = Support::orderBy("created_at","DESC")->withCount("children")->paginate(100);
        return view("back.supports.all",compact("supports"));
    }

    public function show(Support $support){
        return view("back.supports.show",compact("support"));
    }
}

app/Http/Controllers/ChildrenController.php
<?php

namespace App\Http\Controllers;

use App\Events\SupportSubmited;
use App\Http\Resources\ChildrenCollection;
use App\Models\Child;
use App\Models\Support;
use App\Models\User;
use App\Rules\ChildrenSelected;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ChildrenController extends Controller
{
    public function childrenList()
    {
        return new ChildrenCollection(Child::with("tags")->orderBy("priority", "ASC")->limit(60)->paginate(12)->shuffle());
    }

    public function storeSupportList(Request $request)
    {
        $this->validate(
            $request,
            [
                "selected_children" =>[new ChildrenSelected],
                'supporter_name' => "required|max:255",
                "supporter_mobile" => "required|iran_mobile",
            ]

        );
        $children_list = json_decode($request->selected_children);
        $support = new Support();
        $support->selected_children_count = count($children_list);
        $support->supporter_name = $request->supporter_name;
        $support->supporter_mobile = $request->supporter_mobile;
        $support->supporter_address = $request->supporter_address;
        $support->supporter_tell = $request->supporter_tell;
        $support->supporter_national_code = $request->supporter_national_code;
        $support->how_do_you_meet_us = $request->how_do_you_meet_us;
        $support->affiliate_id = User::getAffiliate();
        $support->uuid = Str::random(16);
        $support->save();

        $support->children()->attach($children_list);

        event(new SupportSubmited($support));

        return response()->json([
            "success" => true,
            "uuid" => $support->uuid,
            "support_url" => $support->url
        ]);


    }
}

resources/views/back/children/_form.blade.php
<form action="{{ route('admin.children.store')  }}"
      method="post" enctype="multipart/form-data">
    @csrf
    {{ Html::hidden()->name('child_id')->value($child->id)->when( $action=='edit') }}
    {{ Html::method()->value("PUT")->when($action=='edit') }}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {{
                    Html::text("first_name")
                    ->value(old("first_name",$child->first_name))
                    ->label("نام فرزند")
                    }}
                    {{
                    Html::text("last_name")
                    ->value(old("last_name",$child->last_name))
                    ->label("نام خانوادگی")
                     }}
                    {{
                    Html::text("birth_date_fa_f")
                    ->value(old("birth_date_fa_f",$child->birth_date_fa_f))
                    ->label("تاریخ تولد")
                     }}
                    {{
                    Html::textarea("emotional_text")
                    ->value(old("emotional_text",$child->emotional_text))
                    ->label("متن احساسی")
                    ->description("")
                     }}
                    {{
                    Html::textarea("about")
                    ->value(old("about",$child->about))
                    ->label("درباره")
                    ->description("")
                     }}

                    <div class="row">
                        <div class="col-md-12">
                            <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</form>

resources/views/back/children/all.blade.php
@extends("back.layouts.app")
@section("content_header")
    @component("components.breadcrump",["items"=> ["Dashboard" =>route("admin.dashboard.index"),"current"=>"صف ها"]])
        <a href="{{ route("admin.children.create") }}" class="btn btn-info btn-sm">جدید</a>
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp

@section("content")
    <x-success></x-success>
    {{ $children->render() }}
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>کد ملی</th>
                    <th>نام</th>
                    <th>تاریخ تولد</th>
                    <th>طرح</th>
                    <th>اولویت</th>
                    <th>جنسیت</th>
                </tr>
                </thead>
                <tbody>
                @foreach($children as $child)
                    <tr>
                        <td>{{ $child->national_code }}</td>
                        <td><a href="{{ route("admin.children.edit",$child) }}">{{ $child->full_name }}</a></td>
                        <td>{{ $child->birth_date_fa_f }}</td>
                        <td>{{ $child->type_readable }}</td>
                        <td>{{ $child->priority }}</td>
                        <td>{{ $child->sex_readable }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/back/children/create.blade.php
@extends("back.layouts.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),"Children" =>route("admin.children.index"),"current"=>"معرفی فرزند جدید"]])
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>
    <x-errors></x-errors>
        @include("back.children._form",["action"=>"create"])
@endsection

resources/views/back/children/edit.blade.php
@extends("back.layouts.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.children.index"),"Users" =>route("admin.children.index"),"current"=>"ویرایش اطلاعات فرزند"]])
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>
        @include("back.children._form",["action"=>"edit"])
@endsection

resources/views/back/children/show.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),"Queues" =>route("admin.queues.index"),"current"=>"مشاهده وضعیت صف"]])
    @endcomponent
@endsection
@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")


    <x-success></x-success>
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">
                    اطلاعات صف
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="text-success h4"><i class="fa fa-user"></i> {{ $queue->name }} </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            {{ Html::info()->value($queue->credit_ratio)->label("ضریب کسر اعتبار")->icon("money") }}
                            {{ Html::info()->value($queue->entrance_fee)->label("هزینه ورودی")->icon("money") }}
                            {{ Html::info()->value($queue->simotel_number)->label("داخلی سیموتل")->icon("phone") }}
                        </div>
                        <div class="col-md-6">
{{--                            {{ Html::info()->value($queue->comment)->label("توضیحات")->icon("info") }}--}}
{{--                            {{ Html::info()->value($queue->created_at_fa_ftt)->label("زمان ثبت نام صف")->icon("plus") }}--}}
{{--                            {{ Html::info()->value($queue->updated_at_fa_ftt)->label("زمان آخرین ویرایش")->icon("edit") }}--}}
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-success btn-sm" href="{{ route("admin.queues.edit",$queue) }}"><i
                                class="fa fa-edit"></i> ویرایش مشخصات </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">
                    گزارش
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <calls-report :queue_id="{{ json_encode($queue->id) }}"></calls-report>
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <div class="float-left">

                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">

            <div class="card">
                <div class="card-header">افزودن کاربر به صف</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <x-errors></x-errors>
                        </div>
                    </div>
                    <form action="{{ route('admin.queues.add')  }}"
                          method="post">
                        @csrf
                        {{ Html::hidden()->name('queue_id')->value($queue->id) }}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group ">
                                    <label for="user_select" class="col-form-label text-md-right">نام کاربر</label>
                                    <x-select-user></x-select-user>
                                    <small>کاربر مورد نظر خود را انتخاب کنید</small>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-6">

            <div class="card">
                <div class="card-header">مشاورین حاضر در صف</div>

                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>کاربر</th>
                            <th>داخلی سیموتل</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($queue->users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->simotel_number }}</td>

                                <td>
                                    <form action="{{ route("admin.queues.removeUserFromQueue") }}" method="post">
                                        @csrf
                                        @method("DELETE")
                                        {{ Html::hidden("user_id")->value($user->id) }}
                                        {{ Html::hidden("queue_id")->value($queue->id) }}
                                        <button type="submit" class="btn btn-link text-danger"><i
                                                class="fa fa-window-close "></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-12 mb-4">
            <div class="card ">
                <div class="card-header">
                    آخرین تماس ها
                </div>
                <div class="card-body">
                    @php
                        $report = new \App\Classes\Reports\CallsReports();

                    @endphp

                    <table class="table">
                        <thead>
                        <tr>
                            <th>تاریخ</th>
                            <th>ساعت</th>
                            <th>مدت مکالمه</th>
                            <th>مشاور</th>
                            <th>شماره ورودی</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($report->getCalls($queue->id) as $call)
                            <tr>
                                <td>{{ $call->created_at_fa_f }}</td>
                                <td>{{ $call->created_at->format("H:i:s") }}</td>
                                <td>{{ $call->call_time_readable_short }}</td>
                                <td>{{ $call->user->name }}</td>
                                <td>{{ $call->src_number }}</td>
                                <td>{{ $call->created_at->ago() }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 mb-4">
            <div class="card ">
                <div class="card-header">
درامد مشاورین
                </div>
                <div class="card-body">
                    @php
                        $report = new \App\Classes\Reports\CallsReports();

                    @endphp

                    <table class="table">
                        <thead>
                        <tr>
                            <th>مشاور</th>
                            <th>درامد</th>
                            <th>تعداد تماس</th>
                            <th>مجموع زمان</th>
                            <th>میانگین امتیاز</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($report->usersReport($queue->id) as $report)
                            <tr>
                                <td>{{ $report->user->name }}</td>
                                <td>{{ $report->total_amount }}</td>
                                <td>{{ $report->calls_count }}</td>
                                <td>{{ $report->call_time_readable_short }}</td>
                                <td>{{ $report->poll_score_avg }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection